PROJECT = vdata
PROJECT_DESCRIPTION = Virtue Decentralized Database
PROJECT_VERSION = 0.1.0

DEPS = eleveldb mnesia_eleveldb
dep_mnesia_eleveldb = git https://github.com/klarna/mnesia_eleveldb.git master
dep_eleveldb_commit = 2.2

LOCAL_DEPS = mnesia crypto inets sasl

include ../../erlang.mk
