PROJECT = vkey
PROJECT_DESCRIPTION = Virtue User Addressing
PROJECT_VERSION = 0.1.0

DEPS = base58 bert

dep_base58 = git https://github.com/mhishami/base58.git master
dep_bert = git https://github.com/mojombo/bert.erl.git master

include ../../erlang.mk
